name: ganajec
description: GanaVet AI - Plataforma de predicción de enfermedades bovinas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  provider: ^6.1.2

  # Navegación 2.0
  go_router: ^13.2.0

  # HTTP (única instancia en todo el proyecto)
  dio: ^5.4.3+1

  # Almacenamiento local
  shared_preferences: ^2.2.3

  # Fuentes
  google_fonts: ^6.2.1

  # Gráficas
  fl_chart: ^0.69.0

  # Pagos
  flutter_stripe: ^12.0.2

  # Seguridad — SSL Certificate Pinning
  http_certificate_pinning: ^3.0.0
  crypto: ^3.0.3

  # PDF
  pdf: ^3.10.8
  printing: ^5.13.1

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  # Preview de dispositivos (solo debug/dev)
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/